hinjection/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

from books import views as book_views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='/items/')),

    url(r'^items/?$', login_required(book_views.get_books), name='get_books'),
    url(r'^items/(?P<book_id>\w{0,50})/$', login_required(book_views.get_book), name='get_book'),
    url(r'^items/(?P<book_id>\w{0,50})/(?P<chapter_id>\w{0,50})$',
        login_required(book_views.get_chapter), name='get_chapter'),

    url(r'^admin/books/book/add/?$', login_required(book_views.BookUploadView.as_view()), name='upl'),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login'),

    url(r'^admin/', include(admin.site.urls)),
)

books/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)


class ChapterManager(models.Manager):

    def get_previous(self, chapter):
        if chapter.index_number == 1:
            return None
        return self._get_with_offset(chapter, -1)

    def get_next(self, chapter):
        return self._get_with_offset(chapter, 1)

    def _get_with_offset(self, chapter, offset):
        try:
            return self.get(book=chapter.book, index_number=chapter.index_number + offset)
        except Chapter.DoesNotExist:
            return None

class Chapter(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    book = models.ForeignKey(Book)
    index_number = models.IntegerField()

    objects = ChapterManager()

books/forms.py
from django import forms


class BookUploadForm(forms.Form):
    url = forms.URLField(required=True)

books/views.py
from django.conf import settings
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import FormView

from books import upload
from books.forms import BookUploadForm
from books.models import Book, Chapter


class BookUploadView(FormView):
    success_url = '/admin/books/book'
    template_name = 'upload_book.html'
    form_class = BookUploadForm

    def form_valid(self, form):
        try:
            upload.process_url(form.cleaned_data['url'])
            return HttpResponseRedirect(self.get_success_url())
        except upload.UploadError:
            form.errors['url'] = ['wrong fb2(archive)']
            return render(self.request, self.template_name, {'form': form})


def get_books(request):
    return render(request, 'books.html', {'books': Book.objects.all()})


def get_book(request, book_id):
    try:
        book = Book.objects.get(id=book_id)
    except Exception:
        raise Http404
    return render(request, 'book.html', {'book': book})


def get_chapter(request, book_id, chapter_id):
    try:
        book = Book.objects.get(id=book_id)
        chapter = Chapter.objects.get(id=chapter_id)
    except Exception:
        raise Http404
    spritz_redirect_url = request.build_absolute_uri('{}{}'.format(settings.STATIC_URL, 'login_success.html'))
    previous_chapter = Chapter.objects.get_previous(chapter)
    next_chapter = Chapter.objects.get_next(chapter)
    return render(request, 'chapter.html', {'book': book, 'chapter': chapter, 'next_chapter': next_chapter,
                                            'previous_chapter': previous_chapter,
                                            'spritz_redirect_url': spritz_redirect_url})

books/templates/book.html
{% extends "base.html" %}

{% block body %}
<h1>{{book.title}} | {{book.author}}</h1>

<ul>
  {% for chapter in book.chapter_set.all|dictsort:"index_number" %}
    <li>
        <a href="{% url 'get_chapter' book.id chapter.id %}"> {{chapter.title}}</a>
    </li>
  {% endfor %}
</ul>

{% endblock %}

books/templates/books.html
{% extends "base.html" %}

{% block body %}
<h1>Library</h1>

<ul>
  {% for book in books %}
    <li>
        <a href="{% url 'get_book' book.id %}"> {{book.title}}</a> | {{book.author}}
    </li>
  {% endfor %}
</ul>

{% endblock %}

books/templates/chapter.html
{% extends "base.html" %}

{% block head %}
    <script type="text/javascript" src="//sdk.spritzinc.com/js/1.0/js/spritz.min.js"></script>
    <script type="text/javascript">
        {% include 'javascript/spritz.js' %}
    </script>
{% endblock %}

{% block body %}
<p><div id="spritzer"></div></p>
<div class="menu">
    <input type="button" value="Spritz!" id="startSpritz"/>
    {% if previous_chapter %}
        <form method="get" action="{% url 'get_chapter' book.id previous_chapter.id %}">
            <button type="submit">Previous chapter</button>
        </form>
    {% endif %}
    {% if next_chapter %}
        <form method="get" action="{% url 'get_chapter' book.id next_chapter.id %}">
            <button type="submit">Next chapter</button>
        </form>
    {% endif %}
</div>
<h3><a href="{% url 'get_book' book.id %}">{{book.title}}</a></h3>
<h4>{{chapter.title}}</h4>

<textarea id="inputText" rows="12" cols="43">
    {{chapter.content}}
</textarea>

{% endblock %}

books/templates/upload_book.html
{% extends "admin/index.html" %}
{% block content %}
<form action="{% url 'upl' %}" method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    <input type="submit" id="submit" value="Go" />
    {% csrf_token %}
</form>
{% endblock %}

hinjection/templates/accounts/login.html
{% extends "base.html" %}

{% block body %}
    <header>
        <h4>Hinjection | Login</h4>
    </header>

    <section>
        {% if form.errors %}
            <p>Your username and password didn't match, please try again.</p>
        {% endif %}

        <form method="post" action=".">
            {% csrf_token %}
            <p>
                <label for="id_username">Username:</label>
                {{ form.username }}
            </p>
            <p>
                <label for="id_password">Password:</label>
                {{ form.password }}
            </p>
            {% if next %}
                <input type="hidden" name="next" value="{{ next }}" />
            {% else %}
                <input type="hidden" name="next" value="/" />
            {% endif %}
            <input type="submit" value="login" />
        </form>
    </section>
{% endblock %}
{% block footer %}{% endblock %}

hinjection/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/> <!--320-->
        <script type="text/javascript" src="//sdk.spritzinc.com/jQuery/jquery-2.1.0.min.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}jquery.caret.js"></script>

        <style type="text/css">
            {% include 'style/style.css' %}
        </style>

        <title>Hinjection</title>

        {% block head %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
    <hr>
    <footer>
        <div class="menu">
            <ul>
                {% if user.is_authenticated %}
                    <li>{{ user }}, <a href="/accounts/logout">logout</a></li> |
                    <li><a href="{% url 'get_books' %}">home</a></li> |
                    <li><a href="/admin">admin</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="dev">
            <ul>
                <li>only for development/testing</li>
            </ul>
        </div>
    </footer>
</html>